version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    ports:
      - "8077:8077"
    volumes:
      - ./src:/new/src
      - ./dist:/new/dist

    